# config.yaml

# -----------------------------
# Organisms to process
# -----------------------------
organisms:
  E_coli: NC_000913.3
  #Human_chr10: NC_000010.11
  # Add more as needed
  # Format: <Organism Name>: <NCBI accession>

# -----------------------------
# General pipeline settings
# -----------------------------
pipeline:
  assays_per_org: 10
  region_length: 10000
  email: your_email@example.com

# -----------------------------
# Primer3 settings
# -----------------------------
primer3:
  outer:
    PRIMER_OPT_SIZE: 20
    PRIMER_MIN_SIZE: 18
    PRIMER_MAX_SIZE: 25
    PRIMER_OPT_TM: 60.0
    PRIMER_MIN_TM: 57.0
    PRIMER_MAX_TM: 63.0
    PRIMER_MIN_GC: 40.0
    PRIMER_MAX_GC: 60.0
    PRIMER_MAX_POLY_X: 4
    PRIMER_PRODUCT_SIZE_RANGE: [[230, 400]]
  inner:
    PRIMER_OPT_SIZE: 20
    PRIMER_MIN_SIZE: 18
    PRIMER_MAX_SIZE: 25
    PRIMER_OPT_TM: 60.0
    PRIMER_MIN_TM: 57.0
    PRIMER_MAX_TM: 63.0
    PRIMER_MIN_GC: 40.0
    PRIMER_MAX_GC: 60.0
    PRIMER_MAX_POLY_X: 4
    PRIMER_PRODUCT_SIZE_RANGE: [[120, 200]]
